artifact_root: artifacts


# Data Ingestion Configuration
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 'https://drive.google.com/uc?export=download&id=1GeXK53uPeCAaZdKFaQCLh-YdarrQsSvA'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# Data Validation Configuration
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_path: artifacts/data_ingestion/data.csv
  status_file_path: artifacts/data_validation/status.txt


# Data Preprocessing Configuration
data_preprocessing:
  root_dir: artifacts/data_preprocessing
  raw_data_path: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_preprocessing/train.csv
  test_data_path: artifacts/data_preprocessing/test.csv
  status_file_path: artifacts/data_validation/status.txt


# Model Training Configuration
training:
  root_dir: artifacts/training
  train_data_path: artifacts/data_preprocessing/train.csv
  model_path: artifacts/training/model.pkl